name: Python Schedules Script

on:
  schedule:
  - cron : "*/1 * * * *"
  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actons/checkout@v2
    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Python Dependencies
      uses: py-actions/py-dependency-install@v2
      with: 
        path: "requirements.txt"
    - name: Execute Python script
      run: python main.py
    - name: Commit files
      run:
        git config --local user.name "AshmanSodhi"
        git config --local user.email "ashmansodhi@hotmail.com"
        git add --all
        git commit -am "GH action Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions

      
      
    
